"""empty message

Revision ID: e3df3f35af3e
Revises: 
Create Date: 2021-03-14 20:42:32.128278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3df3f35af3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_information')
    # ### end Alembic commands ###
